### PR TITLE
README: Extends instructions from PR #14

### PR DESCRIPTION
**Pull request by DerGoogler**
This Pull Request extends and add instructions for manual edit and editing via MMRL

orgi: https://github.com/symbuzzer/livebootmodule/pull/14

### CODE REVIEW

**Comment by peternmuller** [comment]
Nice, but be careful, your Note sign isn't correctly formatted:

It should be:
> [!NOTE]
> text....

and not

> [!NOTE] > text...



image
Now

image
Correct formatting

**Comment by peternmuller** [comment]
@DerGoogler

**Comment by DerGoogler** [comment]
Bruh, I have tested that on GitHub and still failed ...🤣

**Comment by DerGoogler** [comment]
@peternmuller there is a link, but is somehow not rendered

**Comment by DerGoogler** [comment]
ok nvm, there was a typo

**Comment by peternmuller** [comment]
@DerGoogler Made a new pr with my changes in addition here https://github.com/symbuzzer/livebootmodule/pull/17
Or you can merge the pr I made in your repo and I can delete the pr here, as you want

**Pull request merged**
